#!/bin/sh
set -e
lb config noauto \
  --mode debian \
  --distribution sid \
  --architectures amd64 \
  --debian-installer false \
  --archive-areas "main contrib non-free non-free-firmware" \
  --mirror-bootstrap "https://repo.tohur.xyz/upstream/" \
  --mirror-binary "https://repo.tohur.xyz/upstream/" \
  --debootstrap-options "--include=apt-transport-https,ca-certificates,openssl" \
  --firmware-binary true \
  --firmware-chroot true \
  --linux-flavours "x64v2" \
  --linux-packages "linux-xanmod" \
  --memtest memtest86+ \
  --bootappend-live "boot=live config splash components username=rakuos user-fullname=RakuOS hostname=rakuos" \
  --iso-application "RakuOS" \
  --iso-publisher "RakuOS Project" \
  --iso-volume "RakuOS Live" \
  "${@}"
